name: Test Workflow
on: push
jobs:
    first_job:
        name: first job
        runs-on: ubuntu-latest
        steps:
        - name: Code Checkout
          uses: actions/Checkout@v3
        - name: Testing Code
          run: cat README.md
    Second_job:
        name: Second job
        runs-on: ubuntu-latest
        steps:
        - name: Deploy code
          run: echo "Code Deployed"


#####


